# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alexey/programming/systemverilog/ethernet_image_transfer/fpga/zynq/zynq.srcs/sources_1/bd/zynq/ip/zynq_v_tpg_0_0/zynq_v_tpg_0_0.xci
# IP: The module: 'zynq_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexey/programming/systemverilog/ethernet_image_transfer/fpga/zynq/zynq.gen/sources_1/bd/zynq/ip/zynq_v_tpg_0_0/zynq_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alexey/programming/systemverilog/ethernet_image_transfer/fpga/zynq/zynq.gen/sources_1/bd/zynq/ip/zynq_v_tpg_0_0/zynq_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alexey/programming/systemverilog/ethernet_image_transfer/fpga/zynq/zynq.srcs/sources_1/bd/zynq/ip/zynq_v_tpg_0_0/zynq_v_tpg_0_0.xci
# IP: The module: 'zynq_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexey/programming/systemverilog/ethernet_image_transfer/fpga/zynq/zynq.gen/sources_1/bd/zynq/ip/zynq_v_tpg_0_0/zynq_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/alexey/programming/systemverilog/ethernet_image_transfer/fpga/zynq/zynq.gen/sources_1/bd/zynq/ip/zynq_v_tpg_0_0/zynq_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
