# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/alexey/Downloads/dsdb/DSDB_Master.xdc

# Block Designs: bd/zynq/zynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_vdma_0_0/zynq_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_vdma_0_0 || ORIG_REF_NAME==zynq_axi_vdma_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_auto_pc_0 || ORIG_REF_NAME==zynq_auto_pc_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_mem_intercon_0/zynq_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_mem_intercon_0 || ORIG_REF_NAME==zynq_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_rst_ps7_0_50M_0/zynq_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_v_tpg_0_0/zynq_v_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_v_tpg_0_0 || ORIG_REF_NAME==zynq_v_tpg_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xbar_0/zynq_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_xbar_0 || ORIG_REF_NAME==zynq_xbar_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_auto_pc_1/zynq_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_auto_pc_1 || ORIG_REF_NAME==zynq_auto_pc_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps7_0_axi_periph_0/zynq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_ps7_0_axi_periph_0} -quiet] -quiet

# XDC: /home/alexey/programming/systemverilog/ethernet_image_transfer/fpga/zynq/zynq.gen/sources_1/bd/zynq/zynq_ooc.xdc
